#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

if [[ ! -f $OPENSHIFT_DATA_DIR/db_imported ]]
then
    pushd $OPENSHIFT_REPO_DIR/php/schema
    psql < ttrss_schema_pgsql.sql
    touch $OPENSHIFT_DATA_DIR/db_imported
fi

