#!/bin/bash
# This is a simple post deploy hook executed after your application 
# is deployed and started.  This script gets executed directly, so 
# it could be python, php, ruby, etc.#!/bin/bash

if [[ ! -f $OPENSHIFT_DATA_DIR/db_imported ]]
then
    pushd $OPENSHIFT_REPO_DIR/php/schema
    psql -f ttrss_schema_pgsql.sql && touch $OPENSHIFT_DATA_DIR/db_imported
fi

